#!/bin/sh


if [ ! -d "$1" ]; then
  echo "The directory $1 does not exist!"
  exit 1
fi

export BORG_REPO=$1
#export BORG_PASSCOMMAND='pass show system/Borg'

# some helpers and error handling:
info() { printf "\n%s %s\n\n" "$(date)" "$*" >&2; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

info "Starting backup"

# Backup the most important directories into an archive named after
# the machine this script is currently running on:

borg create \
	--verbose \
	--filter AME \
	--list \
	--stats \
	--show-rc \
	--compression zstd,10 \
	--exclude-caches \
	--exclude 'home/*/_build/*' \
	--exclude 'home/*/.cache/*' \
	--exclude 'home/*/.config/BraveSofteware/*' \
	--exclude 'home/*/.config/*/Cache/*' \
	--exclude 'home/*/.config/*/CacheStorage/*' \
	--exclude 'home/*/.git/*' \
	--exclude 'home/*/.kube/*' \
	--exclude 'home/*/.npm/*' \
	--exclude 'var/tmp/*' \
	\
	::'{hostname}-{now}' \
	/etc \
	/home \
	/root \
	/var

backup_exit=$?

info "Pruning repository"

# Use the `prune` subcommand to maintain 7 daily, 4 weekly and 6 monthly
# archives of THIS machine. The '{hostname}-*' matching is very important to
# limit prune's operation to this machine's archives and not apply to
# other machines' archives also:

borg prune \
	--list \
	--glob-archives '{hostname}-*' \
	--show-rc \
	--keep-daily 7

prune_exit=$?

# actually free repo disk space by compacting segments

info "Compacting repository"

borg compact

compact_exit=$?

# use highest exit code as global exit code
global_exit=$((backup_exit > prune_exit ? backup_exit : prune_exit))
global_exit=$((compact_exit > global_exit ? compact_exit : global_exit))

if [ ${global_exit} -eq 0 ]; then
	info "Backup, Prune, and Compact finished successfully"
elif [ ${global_exit} -eq 1 ]; then
	info "Backup, Prune, and/or Compact finished with warnings"
else
	info "Backup, Prune, and/or Compact finished with errors"
fi

exit ${global_exit}
